[package]
name = "mega_tool"
version = "0.0.1-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
regex = "1.10.4"
url = "2.5.0"
walkdir = "2.5.0"
clap = { version = "4.5.4", features = ["derive"] }
